### ISSUE TITLE
Experimental push on scalar is now forbidden at DN_SSpred2.pm line 2853

### ISSUE THREAD

**Issue by impulsteve** [multicom-toolbox/DNSS2#1]
Hi,

I followed the installation procedure and tried to do a test prediction on the fasta files in the test directory. But the command immediately results in an abortion:
```
Experimental push on scalar is now forbidden at path/DN_SSpred2.pm line 2853, near "])"
Compilation failed in require at run_DNSS2.pl line 15.
BEGIN failed--compilation aborted at run_DNSS2pl line 15.
```
Looking in the code it somehow is linked to the last line (2853) in the following part, but I am not very known with the perl language:

```
for (my $ii=0; $ii<@input; $ii++){
    my @scores = @{ $input[$ii] };
    for (my $jj=0; $jj<@scores; $jj++){
         push ($data[$jj], $scores[$jj]);
    }
}
```
I followed the installation steps exactly as mentioned and I am not getting much wiser by the answers found on the internet for the "Experimental push on scalar is now forbidden" error

**Comment by impulsteve** [comment]
As an addition, I work in Ubuntu 18.04.3 with perl 5, version 26.

**Comment by impulsteve** [comment]
You'll always see, stuck on this since monday morning and [finding the answer](https://github.com/hitode909/App-PerlPackage2PlantUMLClassDiagram/commit/bf48c554cc5d06e7079daa088a25973c531d5857) right after asking the question, I think at least. For more recent versions of Perl one has to adjust
`push ($data[$jj], $scores[$jj]);`
into
`push (@{$data[$jj]}, $scores[$jj]);`

Now the test prediction with the following command at least starts
`perl run_DNSS2.pl -seq /.../DNSS2/test/1GNY-A.fasta -file -out /.../DNSS2/test` 

But aborts again after an Error that it could not open a file `test//temp/hmm/1GNY-A.aln2profile` (
why a double slash after test?)

Looking in this directory I find the `.a3m`, `.aln`, `.hmm`, `.hmm2freq`, `.hmm2prob` files and a subdirectory 1GNY-A with the `.msa2profile` and `.tmp` files and a typeless `1GNA-Y` file, but the requested ` .aln2profile` file is still absent, hence why it couldn't open the file.

How can I create this file?

**Comment by huge200890** [comment]
Thank you for reporting these issues. The program was developed and tested on 'CentOS' environment with perl version 5.16.   We haven't tested on ubuntu system yet. We are currently testing the program on ubuntu to check the performance. 

1. For the error 'Experimental push on scalar is now forbidden at path/DN_SSpred2.pm line 2853, near "])"', it seems the error will be reported after perl version 5.23 according to online information. One possible solution is using old version such as 5.16. We also probably need go through all codes to fix the issues as you proposed in order to support latest perl version.

2. The double slash shouldn't be the problem. The reason why *aln2profile was not generated might be due to the different operating system. We are investigating the issue by running program on ubuntu. Will update more details when we find the reason. 

Thanks.

**Comment by impulsteve** [comment]
Thanks for the fast response. The experimental push error seems to be only related to `line 2853` of the `DN_SSpred2 `script and adding the `@{ }` around ` $data[$jj]` in that line seemed to solve it. After that the `run_DNSS2.pl` command can run (with the experimental push error it cannot) until the generation of the test file:

```
[08/14/2019 09:20:52]  Generating Alignment Probability...
perl ~/.../projects/DNSS2//scripts/msa2profile_sspro.pl ./test/1GNY-A.fasta ./test//temp/hmm/1GNY-A.aln  ./test//temp/hmm/ ~/.../projects/DNSS2//scripts/msa2profile_sspro ~/.../projects/DNSS2//scripts/sspro.model

sequence length doesn't match with output from SSpro.153 != 1
[08/14/2019 09:20:52]  Generating HMM Probability...
perl ~/.../projects/DNSS2//scripts/gen_transition_prob_fromhmm.pl  ./test/1GNY-A.fasta ./test//temp/hmm/1GNY-A.hmm

[08/14/2019 09:20:52]  Performing SS train & test using the parameters:
Outdir: ./test/
Iterations: 1
Reduced: 0
Skip X: 0

Window: 1
Pssm: 1
Pssm_uniref50: 0
HMMEM: 1
HMMTR: 1
aln_sspro: 0
aln_sspro_unif50: 0
aln_sspro_unif90: 0
aln_hhblits: 1
Atch: 1
Seq: 0
Arch: X,X,0
Boost: 0
Bound: 0

[08/14/2019 09:20:52]  Generating Testing File...
err: features: Couldn't open ./test//temp/hmm/1GNY-A.aln2profile file at ~/.../projects/DNSS2//lib/DN_SSpred2.pm line 717.
```

Thanks again and keep me posted!

Keep up the good work,
Stefan

**Comment by huge200890** [comment]
Hi,
We have fixed the error and tested on Ubuntu 18.04.3 with perl 5.26.1 . Please pull our latest version and test again. Really appreciate your suggestions for the errors. Hope you can run the program successfully this time.

**Comment by impulsteve** [comment]
Thanks! I managed to get it working. Great and keep up the good work.

Cheers,
Stefan
